apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: monolithsvc-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithsvc
  template:
    metadata:
      labels:
        app: monolithsvc
    spec:
      containers:
      - env:
        image: daed.duckdns.org:50000/monolithsvc:kashkaval
        imagePullPolicy: Always
        name: monolithsvc
        resources:
          requests:
            cpu: 0.5
            ephemeral-storage: "10Mi"
            memory: 200Mi
          limits:           
            memory: 200Mi
        ports:
        - containerPort: 8080
      securityContext:
        runAsNonRoot: true
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: monolithsvc
  name: monolithsvc
  namespace: default
spec:
  ports:
  - nodePort: 30881
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: monolithsvc
  type: NodePort
