pipeline:
  identifier: Build_r3adm3_monolithsvc_1706107082261
  name: Build monolithsvc
  orgIdentifier: default
  projectIdentifier: TestProj
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1692803686956
        repoName: r3adm3/monolithsvc
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      dotnet info
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
