pipeline:
  identifier: Build_monolithsvc_1727335675974
  name: Build monolithsvc
  orgIdentifier: default
  projectIdentifier: monolith
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.MyGitHub
        repoName: monolithsvc
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Dockerpi
                    repo: daed.duckdns.org:50000/harness-monolithsvc
                    tags:
                      - latest
                    caching: true
                    dockerfile: ./monolithsvc/Dockerfile
                    context: ./monolithsvc
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Home_Cluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
